---
name: Python Ci
on: null
push:
  branches:
    - main
workflow_dispatch: null
jobs:
  builds:
    run-python:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: set up the python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"
        - name: Run the python code
          run: python app.py

